HaliteChallenge/Halite-III

apiserver/apiserver/coordinator/matchmaking.py
Postgresql has true integer division, resulting in game_curve always being 0 if a player has any games at all and giving no differentiation between players.
=> Fix new bot match seeding.

apiserver/worker/compiler.py
Had some extremely odd compilation errors in Scala. Once I renamed the `RandomBot.scala` file in my project to `MyRandomBot.scala`, my bot started compiling when submitted.
Was this intentional?
=> Remove special-casing for "RandomBot" in compiler

website/javascript/templates/Play.vue
Validation for zip uploads only allows MIME type === "application/zip" when some browsers report other MIME types
=> Fix missing validation on zip MIME types

tools/hlt_client/hlt_client/compare_bots.py, tools/hlt_client/hlt_client/gym.py
It was mentioned in passing on Discord that the gym played with the wrong map sizes. This removes the gym explicitly specifying a map size so that the engine will choose on its own.
It also makes it so the the client will default to the engine map choice.
=> By default have hlt client let the engine choose the map size.

tools/nightmare/nightmare.py
I notice when trying to feed the output of nightmare to my client that nightmare failed to output the map cell update count per game frame, which was easy enough to fix.
=> Bugfix for missing map update count in nightmare tool

website/_sass/_game-feed.scss, website/_sass/_user-profile.scss
Currently in the game feed the background for challenge games is much too
dark, making it hard to read player names.
On other hand the player profile page sets the challenge game background
to the same color as other games.
This changes to a light cyan color for both pages.
Current game feed:
New game feed:
New player profile feed:
=> Set more reasonable challenge game highlighting.

starter_kits/Go/src/hlt/Entities.go, starter_kits/Go/src/hlt/Player.go
It'd be helpful if we can make Entity.id a readable value to our own implementation. I'm porting my Python implementation to golang which relies on Ship.id being a readable value in a number of cases.
golang's Ship instance only provides a pointer to Position, which is significantly less convenient to work with. Example from my own implementation: near the middle/end of each turn, each ship AI returns a slice of their preferred moves on the next turn descending by preference. Each ship's actual move is decided by a swarm AI which helps avoid collisions and optimize overall positions. Without Entity.id accessible, we need to generate our own ID for each ship and perform a mix of internal accounting operations between swarm AI and ship AIs to track which ship ID is where based on the …
=> golang starter kit: adds Player.GetShip(shipId) method and makes Entity.id and Ship.E.id accessible.

game_engine/main.cpp
The option was only setting `constants.MAX_TURNS`, the actual result of this is dependent on the map size and limit set. But if the map size was larger than `constants.MIN_TURN_THRESHOLD` and the limit set was less than `constants.MIN_TURNS` this would result in some very large turn limit actually being used. Thanks, unsigned integer math.
Problem initially reported [on the forums by nkelly13](https://forums.halite.io/t/no-effect-from-turn-limit-option-to-halite-cli/551).
=> Fix engine turn limit option.

website/javascript/templates/TierPopover.vue
The TierPopover was using a 1 based index, while recent changes assumed a 0 based index. This just brings everything back inline with 1 based indexing.
=> Fix an off by one error on tier icon indexing.

starter_kits/Go/src/hlt/Position.go
Let's make Position coordinates available so they don't need to be extracted from the String() representation.
=> [Go starter kit] Enable developers to instantiate hlt.Position and make its coordinates available.

starter_kits/PHP/hlt/Player.php
Currently dropoffs are being stored as ships causing the typechecking of some of the later PHP functions to fail. This corrects the typo.
=> PHP Starter Bot: Fixed bug where dropoffs where being stored into the ships array

apiserver/worker/compiler.py
@lidavidm thanks but it didn't work. (ERROR: syntax: invalid identifier name ".") I'm guessing this is a bash error maybe. Either way I removed the activate(".") step since instantiate() should pick up the manifest in the current directory.
=> julia starter bot

starter_kits/Go/src/hlt/Game.go
Can we give Game.players the same accessibility as Java/Python hlt packages?
The challenge: Identifying attractive dropoff locations while excluding locations within N proximity of other player shipyards and dropoffs. This data is available via Game.Map.Cells, but requires linear checking of every cell on the map. Java/Python implementations make data about opposing players available directly -- ref: https://github.com/HaliteChallenge/Halite-III/blob/master/starter_kits/Java/hlt/Game.java#L9
=> [Go starter kit] Give Game.players same accessibility as Java/Python starter kits.

game_engine/core/HaliteImpl.cpp
- "Last turn alive" was off by 1 turn
- Don't set player energy to 0 after they are ejected (terminated players aren't asked for moves anyways)
- Keep tracking some stats after a player is ejected so they can be ranked properly
Fixes #148.
=> Properly rank players that don't have halite to proceed

starter_kits/CSharp/Halite3/hlt/Position.cs
Added the get surrounding cardinals function to the position class, as found in some of the other starter kits.
=> Added GetSurroundingCardinals() to C# Starter Kit

starter_kits/Python3/hlt/entity.py, starter_kits/Python3/hlt/positionals.py
A nice way to speed things up is to pre-compute things and save them in a dict. For example:
```python
distance_by_position = {p: game_map.calculate_distance(ship.position, p) for p in positions}
```
You can then use it very easily in the built in functions min, max, sorted, etc.:
```python
sorted_positions = sorted(positions, key=distance_by_position.get)
best_position = min(positions, key=distance_by_position.get)
```
As of now, both Position and Entities are not hashable, meaning you can't use them as keys in a dict, or even save them in a set.
This PR implements the __hash__ method for both Position and Entity, making the above possible.
=> Making Entity and Position hashable in Python3 starter kit

game_engine/core/command/Transaction.cpp
This change is a potential fix for #172 and makes the engine actually spawn a ship even when it immediately crashes into an existing ship. This allows all events to occur and fixes the `all_collisions` and `self_collisions` counts in the player statistics.
One part I'm unsure of with this change is that it causes `entity_updated` to be called before `cell.entity` is set.
Even with this change the visualizer collision count when watching a replay is still incorrect. I haven't looked into why that is yet.
=> Fully spawn a ship even when it immediately crashes.

starter_kits/Python3/hlt/constants.py, starter_kits/Python3/hlt/networking.py, starter_kits/Python3/hlt/positionals.py
This closes #78.
This PR adds WIDTH and HEIGHT to constants, and adds a new `normalize` method to Position. This allows positions to be normalized without having to use the game map.
Further, Position is then modified to auto normalize itself in the constructor.
I believe this is necessary because of the consequences of not auto normalizing Positions. As I'm sure many of you are aware, Path Planning algorithms depend heavily on not expanding positions they've already evaluated. But, as a consequence of not auto normalizing positions, naive use of the Position class will result in much more work than expected. This is because Position equality and hashing does not take into account the width and height of the game. This leads to this effect in a 32x32 board:
```
>>> Position(0, 0) == …
```
=> Auto normalizing positions for python starter kit

game_engine/core/HaliteImpl.cpp
Fixes #178 
This makes the final stats and player ranks get calculated correctly.
I believe this is the correct thing to do here, but not completely confident that it won't cause other issues. In particular that there isn't something else that is depending on the turn number not incrementing when the game ended early.
This does fix the issue with a player that is terminated on the last turn but having more halite than the last player alive ranking above them.
=> Increment turn number when ending the game early

starter_kits/Python3/hlt/game_map.py
The original distance is calculated by subtracting two points.  Looking at positional.py, we know that by default, this coordinate would be normalized.
So lets say we want to move from `(14,24)` to `(12,24)`.  The distance would be `(46,0)`, which caused the get_unsafe_moves function to think they can go faster by choosing the inverted direction, so we get a direction of `[ (1,0) ]`, but intuitively, we would want `[ (-1,0) ]`
By changing how the distance is calculated, we avoid this situation.
=> Update distance calculation in get_unsafe_moves

apiserver/apiserver/coordinator/matchmaking.py, apiserver/apiserver/scripts/rating_reset.py
- Fixes the matchmaking seed player query for PostgreSQL (use RANDOM instead of RAND)
- Update the ranking reset to use the reflected `bot_rank` column (instead of splicing text into the query)
Fixes #196.
=> Minor tweaks to finals setup

apiserver/worker/compiler.py
Julia uses lazy compilation and compiles code when it is first used. Before this PR bots written in Julia are compiled when the code if first used, i.e during the initialization phase. This unfairly limits the amount of code and packages that can be used in Julia projects.
This PR triggers compilation of Julia projects during the compilation phase of Halite3.
=> Compile Julia bots during compilation phase
