- website/learn-programming-challenge/api-docs.md
> Fix api document dropoff typo.

- website/learn-programming-challenge/contributing.md
Correcting a false statement in the starter kit guide.
> Only dropoffs are sent each turn

- apiserver/apiserver/coordinator/matchmaking.py
Should fix challenge matchmaking.
> Prefer challenges that haven't played over challenges that have

- starter_kits/Scala/hlt/Ship.scala
make halite amount on the ship available externally
> halite is not accessible

- game_engine/main.cpp
> Make '--results-as-json' compatible with '--no-replay'

- starter_kits/Java/hlt/Position.java
regarding #40 
Also made directionalOffset public so the player can access it.
> implemented getSurroundingCardinals

- website/javascript/templates/HaliteTV.vue
- website/javascript/templates/Onboarding.vue
- website/javascript/templates/Play.vue
- website/javascript/templates/VisualizerContainer.vue
Guide users to force refresh the page upon visualizer replay error.
> Viz error msg

- game_engine/core/command/CommandTransaction.cpp
> Fix segfault in check that player owns entity in command

- starter_kits/PHP/.gitignore
- starter_kits/PHP/app.php
- starter_kits/PHP/hlt/Command.php
- starter_kits/PHP/hlt/Constants.php
- starter_kits/PHP/hlt/Direction.php
- starter_kits/PHP/hlt/Dropoff.php
- starter_kits/PHP/hlt/Entity.php
- starter_kits/PHP/hlt/EntityId.php
- starter_kits/PHP/hlt/Game.php
- starter_kits/PHP/hlt/GameMap.php
- starter_kits/PHP/hlt/Input.php
- starter_kits/PHP/hlt/Logger.php
- starter_kits/PHP/hlt/MapCell.php
- starter_kits/PHP/hlt/Player.php
- starter_kits/PHP/hlt/PlayerId.php
- starter_kits/PHP/hlt/Position.php
- starter_kits/PHP/hlt/Ship.php
- starter_kits/PHP/hlt/Shipyard.php
- starter_kits/PHP/run_game.bat
- starter_kits/PHP/run_game.sh
> Add PHP Starter Kit

- apiserver/apiserver/web/challenge.py
This just duplicates the query used in list challenges helper.
> Fix challenge participant query for challenge summary api.

- .travis.yml
Closes #85 
Since it looks like my PR #33 will get closed via #30 , pulling this out here. 
Pre-req merge: #30
> Add Ruby starter kit check

- apiserver/worker/compiler.py
- starter_kits/Julia/.gitignore
- starter_kits/Julia/Manifest.toml
- starter_kits/Julia/MyBot.jl
- starter_kits/Julia/Project.toml
- starter_kits/Julia/README.md
- starter_kits/Julia/run_game.bat
- starter_kits/Julia/run_game.sh
- starter_kits/Julia/src/Halite3.jl
- starter_kits/Julia/src/commands.jl
- starter_kits/Julia/src/constants.jl
- starter_kits/Julia/src/game_map.jl
- starter_kits/Julia/src/networking.jl
- starter_kits/Julia/src/positionals.jl
A rough draft but it is working. ~~Probably needs some commenting, and~~ Probably has some bad code which will error once it is hit.  Also I changed the apiserver compiler.py julia language specifications it would be helpful if someone could verify it is building correctly.
> Julia starter bot

- starter_kits/Python3/hlt/game_map.py
- starter_kits/Python3/hlt/player.py
Fixes #83 
I don't see any unit tests, but I ran a local ./run_game.sh and confirmed everything works as expected. This simply copy/pastes the Player class into a file where it's easier to find when getting familiarized with the Python starter kit.
> Move Player.py from game_map.py to player.py

- website/javascript/templates/Visualizer.vue
> 10x replay speed added on watch games

- starter_kits/Swift/Halite-III/Halite-III/hlt/Command.swift
- starter_kits/Swift/Halite-III/Halite-III/hlt/Direction.swift
- starter_kits/Swift/Halite-III/Halite-III/hlt/Game.swift
- starter_kits/Swift/Halite-III/Halite-III/hlt/Networking.swift
- starter_kits/Swift/Halite-III/Halite-III/hlt/Ship.swift
While the swift starter kit I submitted over the weekend (#112) compiled, it had a few bugs that I discovered after trying to use it to write my bot. Specifically:
* I misunderstood the command format, so the bot couldn't create ships, move ships, or do anything than just sit there with its initial Halite until time ran out.
* Oh, and I never actually recorded the player's Halite. So the players would incorrectly show a `haliteAmount` of 0 for the entire game.
This fixes both of those issues
> Fix swift starter

- starter_kits/OCaml/MyBot.ml
- starter_kits/OCaml/README.md
- starter_kits/OCaml/build.sh
- starter_kits/OCaml/debug.ml
- starter_kits/OCaml/game.ml
- starter_kits/OCaml/networking.ml
- starter_kits/OCaml/type.ml
This starter doesn't closely conform to the recommended API. It's part way between the API and fohristiwhirl's minimal input-processing starter (probably a little closer to the API).
I wasn't going to go through the official submission process, but a closer reading of the rules reveals that if anyone used this starter package which I linked to in the forum then they could be disqualified for plagiarism, so I thought I should submit it properly, imperfect as it is.
> Add OCaml starter package

- starter_kits/Go/src/MyBot.go
- starter_kits/Go/src/hlt/Entities.go
- starter_kits/Go/src/hlt/Game.go
- starter_kits/Go/src/hlt/GameMap.go
- starter_kits/Go/src/hlt/Player.go
- starter_kits/Go/src/hlt/gameconfig/Constants.go
- starter_kits/Go/src/hlt/input/Input.go
This does 2 things:
1) Fix a bug in IsFull()
2) Use local imports for ease of use.
> Improvements to Go starter kit

- apiserver/apiserver/login/__init__.py
- apiserver/worker/compiler.py
- apiserver/worker/worker.py
- game_engine/core/HaliteImpl.cpp
- website/learn-programming-challenge/downloads.md
Fixes #120.
Fixes #138.
Flamegraphs:
> Reduce CPU usage, fix compilation

- tools/hlt_client/README.md
- website/learn-programming-challenge/contributing.md
- website/learn-programming-challenge/downloads.md
This PR also revises the starter kit design advice as per Issue #88, clarifies copyright issues for starter kits, and reorganizes the downloads page slightly.
> Add documentation for hlt_client

- starter_kits/Clojure/hlt/app/MyBot.clj
- starter_kits/Clojure/hlt/app/halite3/mybot.clj
- starter_kits/Clojure/hlt/lib/hlt/commands.clj
- starter_kits/Clojure/hlt/lib/hlt/direction.clj
- starter_kits/Clojure/hlt/lib/hlt/dropoff.clj
- starter_kits/Clojure/hlt/lib/hlt/game.clj
- starter_kits/Clojure/hlt/lib/hlt/game_map.clj
- starter_kits/Clojure/hlt/lib/hlt/input.clj
- starter_kits/Clojure/hlt/lib/hlt/log.clj
- starter_kits/Clojure/hlt/lib/hlt/map_cell.clj
- starter_kits/Clojure/hlt/lib/hlt/player.clj
- starter_kits/Clojure/hlt/lib/hlt/position.clj
- starter_kits/Clojure/hlt/lib/hlt/random.clj
- starter_kits/Clojure/hlt/lib/hlt/ship.clj
- starter_kits/Clojure/hlt/lib/hlt/shipyard.clj
- starter_kits/Clojure/hlt/lib/hlt/state.clj
- starter_kits/Clojure/make-zip
- starter_kits/Clojure/project.clj
- starter_kits/Clojure/run_game.bat
- starter_kits/Clojure/run_game.sh
Follows the Python3 API insomuch as possible while keeping the Clojure code idiomatic.
> Add clojure starter kit

- starter_kits/Clojure/hlt/lib/hlt/game_map.clj
- starter_kits/Clojure/hlt/lib/hlt/position.clj
- starter_kits/Clojure/make-zip
- starter_kits/Clojure/test/hlt/game_map_test.clj
[@GregA100k] Fixes naive navigate (and several other functions) to take either positions (or extract the position from entities) passed as arguments.
> Updates the Clojure starter kit

- game_engine/networking/common/Networking.cpp
- starter_kits/Python3/hlt/constants.py
- starter_kits/Python3/hlt/game_map.py
- starter_kits/Python3/hlt/networking.py
- starter_kits/Python3/hlt/player.py
- starter_kits/Python3/hlt/positionals.py
> Fix Python starter kit

- game_engine/core/HaliteImpl.cpp
- game_engine/test/integration_test.py
- game_engine/test/integration_test_bot.py
Crashed bots improperly had `last_turn_alive` updated at the end of the game.
Fixes #180.
> Testing & fixes for ranking
